version: "3"

services:
  back_app:
    depends_on:
      - mongodb
    restart: always
    build: .
    ports:
      - "${PORT}:80"
    volumes:
      - .:/usr/src/app
      - .:/usr/src/app/files
    environment:
      - BIKES=${BIKES}
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGODB_DATABASE=${DB_NAME}
    ports:
      - ${DB_PORT}:27017
volumes:
  mongodata:
