version: '3'

services:
  back_app:
    depends_on:
      - mongodb
    restart: always
    build: .
    ports:
      - "4200:4200"
    environment:
      - BIKES=development
      - HOST=localhost
      - PORT=4200
    volumes:
      - .:/usr/src/app
      - .:/usr/src/app/files
  mongodb:
    restart: always
    image: mongo:latest
    volumes:
      - mongodata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=cash
      - MONGO_INITDB_ROOT_PASSWORD=123
      - MONGODB_DATABASE=bikes
    ports:
      - 27017:27017
volumes:
  mongodata:
